### ISSUE TITLE
USA-UDACITY: Unable to load class 'javax.xml.bind.annotation.XmlSchema'.

### ISSUE THREAD

**Issue by sakibguy** [udacity/ud843-QuakeReport#121]
```
Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:86)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy32.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:83)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:80)
	at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1393)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:80)
	... 89 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:162)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:80)
	at com.android.sdklib.repositoryv2.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:69)
	at com.android.builder.sdk.DefaultSdkLoader.init(DefaultSdkLoader.java:115)
	at com.android.builder.sdk.DefaultSdkLoader.getSdkInfo(DefaultSdkLoader.java:97)
	at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:125)
	at com.android.build.gradle.BasePlugin.ensureTargetSetup(BasePlugin.java:680)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:617)
	at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:572)
	at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:569)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
	at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:568)
	at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:565)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	... 99 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	... 119 more
```

# Sna p
![1](https://user-images.githubusercontent.com/24685590/147097741-29790c79-f69f-4c89-a4b2-c240a0c347f0.PNG)

**Comment by sakibguy** [comment]
# Fixed 
> 1-got solution idea: https://github.com/udacity/ud839_Miwok/issues/241#issuecomment-886857724

> 2-tried also but no need if works 1 https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a/64389804#64389804

### Update build.gradle (Project level)
```
dependencies {
        // classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'com.android.tools.build:gradle:4.2.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```
### Proof 
![1](https://user-images.githubusercontent.com/24685590/147103533-af702442-7c31-4ddf-9940-ad3ec5384b6b.PNG)
