### ISSUE TITLE
Setting GradientDrawable to StateListDrawable causes ClassCastException

### ISSUE THREAD

**Issue by yugantjoshi** [udacity/ud843-QuakeReport#70]
```
// Set the proper background color on the magnitude circle.
// Fetch the background from the TextView, which is a GradientDrawable.
GradientDrawable magnitudeCircle = (GradientDrawable)magnitude.getBackground();

// Get the appropriate background color based on the current earthquake magnitude
int magnitudeColor = getMagnitudeColor(currentEarthquake.getMagnitude());
 
// Set the color on the magnitude circle
 magnitudeCircle.setColor(magnitudeColor);
```
The cast to a GradientDrawable causes a Fatal Exception 

logcat:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.android.quakereport, PID: 9509
                                                 java.lang.ClassCastException: android.graphics.drawable.StateListDrawable cannot be cast to android.graphics.drawable.GradientDrawable
                                                     at com.example.android.quakereport.EarthquakeAdapter.getView(EarthquakeAdapter.java:43)
                                                     at android.widget.AbsListView.obtainView(AbsListView.java:2358)
                                                     at android.widget.ListView.makeAndAddView(ListView.java:1876)
                                                     at android.widget.ListView.fillDown(ListView.java:702)
                                                     at android.widget.ListView.fillFromTop(ListView.java:763)
                                                     at android.widget.ListView.layoutChildren(ListView.java:1685)
                                                     at android.widget.AbsListView.onLayout(AbsListView.java:2160)
                                                     at android.view.View.layout(View.java:16692)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5449)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                     at android.view.View.layout(View.java:16692)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5449)
                                                     at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
                                                     at android.view.View.layout(View.java:16692)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5449)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                     at android.view.View.layout(View.java:16692)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5449)
                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                     at android.view.View.layout(View.java:16692)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5449)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                     at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2707)
                                                     at android.view.View.layout(View.java:16692)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5449)
                                                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2173)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1933)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1109)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6046)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:152)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5507)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by foffux** [comment]
Same problem
Not able to overcome it
Any suggestions?
Thank you.

**Comment by yugantjoshi** [comment]
@foffux no I couldn't find a solution for this specific issue. I decided to move forward with other parts instead

**Comment by contemsolutions** [comment]
It appears when you remove these 2 lines below, it works but the colour of the circles do not match the app example

GradientDrawable magnitudeCircle = (GradientDrawable) magnitudeTextView.getBackground();

And

magnitudeCircle.setColor(magnitudeColor);

**Comment by NoctisCaellum** [comment]
@foffux  Do you already found out the way for fix it that error ? Because heppened the same with me

**Comment by Oluflourish** [comment]
Add `android:background="@drawable/magnitude_circle"` to the magnitude TextView in the earthquake_list_item.xml
I also had the same issue. But this worked for me.

**Comment by Nagu07** [comment]
Same error can anyone help!!

**Comment by Kvaibhav01** [comment]
@Nagu07, did you acknowledged [this ](https://github.com/udacity/ud843-QuakeReport/issues/70#issuecomment-318917843)comment? It might be the solution.

**Comment by Nagu07** [comment]
@Kvaibhav01 thank you for response i had included selector element in my drawable layout that was causing the issue... now it is fixed

**Comment by Kvaibhav01** [comment]
@Nagu07, time to close the issue!

**Comment by arsenalabu** [comment]
It took me a while to make the connection between Nagu07's solution and the code, so for anyone as slow as me, a solution to this problem is to replace the word "selector" in Magnitude_circle with "shape".

**Comment by Rohit-2602** [comment]
remove the selector tag from your drawable(xml file for circle). 
Hope this Works!

**Comment by shivam56970** [comment]
remove the selector tag from your drawable(xml file for circle
and also the xnls one which is red underlined and try to check the app after few steps not at the end

**Comment by ahmedmagdy492** [comment]
your magnitude_circle should look like this:
`<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid android:color="@color/magnitude1" />
    <size
        android:width="36dp"
        android:height="36dp" />
    <corners android:radius="18dp" />
</shape>`

otherwise the drawable type will be of type StatelistDrawable so it will throw exception that the casting is not valid
